src/compile.sh
src/compile_opt.sh

Remove src/compile.sh and src/compile_opt.sh because they are not necessary to compile Mandyoc 
Fix #19

Remove compile files from src folder

---

src/sp.cpp

I only eliminate the number of zeros before the dot in the name. 
I want to add the option to save this outputs in binary, but I'm not sure if I can do it 
If you accept this change (@rafaelmds, @victorsacek ), please merge this PR before merge the PR number #27

Rename the output file called sp_surface_global

---

CONTRIBUTING.md
Makefile
test/testing_result.py

I used the reviewer recommendation and change MPI_PATH for MPIEXEC for the test option. 
```
-MPI_PATH = ${PETSC_DIR}/${PETSC_ARCH}/bin
+MPI_PATH = ${PETSC_DIR}/${PETSC_ARCH}/bin/mpirun
test_mandyoc:
@echo "Run MANDYOC test may take several minutes.."
-	cd test/testing_data/ ; ${MPI_PATH}/mpirun -n 2 ../../mandyoc
+	cd test/testing_data/ ; ${MPIEXEC} -n 2 ../../mandyoc
pytest -v test/testing_result.py
```
[https://github.com/openjournals/joss-reviews/issues/3551](https://github.com/openjournals/joss-reviews/issues/3551)

Improve Makefile changing the MPI variable for the test

---

Makefile

This remove the definition of MPIEXEC added by #39.
It' not the best option to define MPIEXEC explicitly otherwise make would not utilize system's MPI.
Fix #42

fix MPIEXEC in Makefile

---

.gitignore
CONTRIBUTING.md
Makefile
docs/files/installation.rst

In the Makefile and installation instruction, I removed the  default  path to $HOME/petsc. 
- Remove the default path for pests at ~
- Add instruction to  add a symlinks of mpirun
- Add instruction to create an env variable for PETSC_DIR before build Mandyoc

Remove default petsc path in the Makefile and istallation

---

Makefile

Fix #59 
This reverts naming and fix variable name used to build the executable inside the new `bin` folder.

fix broken makefile

---

.github/workflows/publish-release.yml
.gitignore
docker/dependencies/Dockerfile
docker/mandyoc/Dockerfile
env/requirements.txt

Add a docker image for a base environment (dependencies) and an image with mandyoc installed.
This will need to be merged after PR #55, so some changes might be needed due Makefile changes.
Some working on tests will be needed as well, so we can use this image to run automated tests.
Fixes #24 (and take over #29).
Partially addresses #53.
Base (dependencies) images: https://hub.docker.com/r/ggciag/mandyoc-dependencies

Add docker images

---

docs/files/benchmarks.rst

Some missing white space in figure legend was causing a cross reference error and hence not numbering figures correctly.
This just add missing space to fix this cross reference error.

fix cross reference error

---

src/DMSwarm.cpp

Changes the allocated space for some arrays related to particles operations.
Fix #62

WIP - fix particle swarm memory access out of range

---

docs/files/installation.rst

Revision of installation instructions.
- Clarify software requirements and dependencies
- List python and python packages correctly
- Adjust and simplify example of petsc installation
- Clarify use of petsc external packages (for direct solver)
Addresses #46.

Improve installation instructions

---

docs/files/installation.rst

I already manually published a [docker image](hub.docker.com/r/ggciag/mandyoc) for mandyoc.
Currently, the workflow is set up to publish on published releases.
This adds information about this docker image option to documentation, in the `How to install` section, which points to the Docker Hub repository, where there is more information about how to use the image.

Add section about docker image

---

docs/files/installation.rst

Fix typos.
[Minor points](https://github.com/ggciag/mandyoc/issues/46#issuecomment-1067238655) from #46.

Fix typos in install instructions

---

docs/files/installation.rst

Improve petsc installation section.
[Minor points](https://github.com/ggciag/mandyoc/issues/46#issuecomment-1067238655) from #46.

Add note about Fortran compiler

---

docs/files/implementation.rst
docs/files/refs.bib

Describes in the Documentation the algorithm used to simulate convergence of the velocity field in the non-linear flow.
Addresses Issue #78.

Documentation: information about the algorithm used in the non-linear flow

---

paper/paper.md

Explicit citation that Mandyoc is a 2D code in the paper

---

docs/files/installation.rst

Add numpy as requirement for running the tests. Add a `cd mandyoc` line after
cloning the repo. Add a note instructing to create `~/.local/bin` before creating
the `mpirun` symbolic link. Fix typo in "petsc". Add requirements for building
PETSc. Fix typo in "versions".
I've made a few changes to the "How to install" section of the docs after installing PETSc and Mandyoc following it.
Most of the changes are based on that experience. Feel free to edit them, they are just proposals!
Thanks for hard work of maintaining and documenting Mandyoc!

Changes to the "How to install" section of the docs

---

src/DMSwarm_2d.cpp
src/DMSwarm_3d.cpp
src/header.h
src/main.cpp
src/options.cpp

Fixes #97
Additionally, a new command is available: `-strain_seed_constant`.
This command expects a logical (true or false) value.
It defaults to `true` to keep the code compatible to previous versions.
If `false` is specified, then the values passed via `-strain_seed` command are summed over to the `random_initial_strain` value. Otherwise, the values are used as constant values.

Fix strain seed command

---

docker/mandyoc/Dockerfile

Fixes #107 
This PR just add the `make all` call in the chain of commands to build Mandyoc, in the Dockerfile.

add missing command to build mandyoc

---

tests/run_tests.sh

Fixes #108 
This PR just fix a typo in test script.

fix typo in line break character

---

src/main.cpp
src/options.cpp
src/reader.cpp

This PR just invert the parse order of params and options.
This change is being made in order to make it easy to merge RP#106.
In future versions, command line options will be removed completely and will not be supported.
NOTE: This change assumes a default (hard coded) upper limit for the number of layers: 100000. This limitation will be removed since we drop support to command line options, specifically `-seed` related options.

Change order of parse options function

---

src/main.cpp

This fix the comparison of the number of layers parsed with the `-seed` command and the number of layers in the `interfaces.txt` file.

Fix comparision of number of layer from -seed command and interfaces file

---

src/DMSwarm2mesh.cpp
src/header.h
src/reader.cpp

Incorporates the shear heating term in the energy equation.

Shear heating

---

src/sp.cpp

Fix typo: add missing `;` to variable declaration.

add missing ;
