examples/Crameri2012_case2/run.sh

add missing run (example) script to Crameri example

---

examples/Crameri2012_case2/README.md
examples/continental_rift/README.md

Add description for crameri and continental rift examples

---

README.md

Correct the links to the contributing guide file, license file and code of conduct file.
Fix #1

Fix links in README file

---

paper/paper.md

I changed thermo-chemical to thermochemical, a relatively more used term. I also fixed a small typo of a verb.

Small text changes

---

src/DM1_v.cpp
src/DMv.cpp

Fixes #21 
I just deleted those not used variables.
@victorsacek could you check it?

Fixes -Wunused-but-set-variable warnings

---

AUTHORS.md

@aguspesce @jamisonassuncao 
Would you like to add your emails?
@victorsacek I added your email, ok?

add developers info

---

.github/workflows/build-doc.yml

update build-docs-web action to trigger only for changes in *docs* folder

---

docs/files/benchmarks.rst
docs/files/installation.rst

Improve documentation to better present the examples and how to run them.
Fixes #23

add information about examples

---

docs/files/implementation.rst

docs: fix expression for viscosity component

---

CONTRIBUTING.md
docs/files/installation.rst

Add notes about mpiexec variable

---

src/DMT.cpp
src/main.cpp
src/veloc_total.cpp

During the simulation, we added a few sentences to facilitate the reading of the model progression.
This PR is related to Issue #49.

Model progression

---

docs/files/benchmarks.rst

Pin Mandyoc version for benchmarks.
Addresses #51.

add mandyoc version for Crameri benchmark

---

docs/files/installation.rst

Add the information about the jupyter notebook and remove the
information about .py scripts

 Fix the documentation about installation.

---

docker/dependencies/Dockerfile

Update docker dependencies to the version showed on docs.

update docker dependencies

---

src/calc_visc.cpp

Incorporate the diffusion creep law for the Wet Olivine (rheol = 19).

Diffusion creep

---

Makefile
src/DM1_2d.cpp
src/DM1_3d.cpp
src/DM1_v.cpp
src/DMSwarm2mesh.cpp
src/DMSwarm_2d.cpp
src/DMSwarm_3d.cpp
src/DMSwarm_move.cpp
src/DMT.cpp
src/DMv.cpp
src/calc_drho.cpp
src/header.h
src/main.cpp
src/options.cpp
src/reader.cpp
src/sp.cpp
src/thermal_Ke.cpp
src/veloc_total.cpp

This is first attempt to include the 3D version of the code.

WIP - Initial version for 3D mode

---

src/calc_visc.cpp
src/header.h
src/reader.cpp

Incorporation of the plasticity option in the param.txt file.
Default value is true. Only relevant in non-linear rheology.
When plasticity=off, the model rheology is only viscous.

Plasticity option

---

docs/files/benchmarks.rst
docs/files/refs.bib

Corrections and additional information about nonlinear rheology benchmarks (punch and slab detachment).

Documentation corrections

---

Makefile

fix new line typo in Makefile

---

src/reader.cpp

This fixes an issue of some PetscScalar/PetscReal values not being broadcast correctly.

Fix wrong values being broadcast

---

src/DMSwarm_move.cpp
src/header.h
src/main.cpp
src/reader.cpp
src/sp.cpp
src/sp_mode.h

This PR
- refactor structure for surface processes
- add new sp modes
- allow for variable rate of sedimentation (for sp_mode sedimentation_rate_limited) via input file "sedimentation_rate.txt" 
- allow for multiple sediment layers via input file "sediment_layers.txt"

Refactor surface processes
